### ISSUE TITLE
this is Black Mailing for get Money

### ISSUE THREAD

**Issue by m9734** [409H/EtherAddressLookup#1040] opened 2018-11-27 14:19 UTC
thos black mailing for get money how much money you want to end your back mailing

**Comment by m9734** [comment] 2018-11-27 14:21
how much money you want because you are black meller

**Comment by 409H** [comment] 2018-11-27 14:44
I am not black mailing anyone. The domain - I assume is empowr - was blacklisted as they are sending private keys to their backend.

Closing. Duplicate of https://github.com/409H/EtherAddressLookup/issues/1038

**Closed by 409H** 2018-11-27 14:44 UTC
