### ISSUE TITLE
Empowr

### ISSUE THREAD

**Issue by ivlim** [409H/EtherAddressLookup#1090] opened 2019-03-10 17:12 UTC
EMPOWR ei ole pahavara.!
https://github.com/409H/EtherAddressLookup/issues/105
https://github.com/409H/EtherAddressLookup/issues/10437

**Comment by 409H** [comment] 2019-03-12 21:56
Closing. Duplicate of https://github.com/409H/EtherAddressLookup/issues/1038

**Closed by 409H** 2019-03-12 21:56 UTC
