### ISSUE TITLE
webpage blacklisted

### ISSUE THREAD

**Issue by LearnerSam** [409H/EtherAddressLookup#1043] opened 2018-11-28 00:51 UTC
I have been trying to open www.empowr.com but this is the message a receive in the browser
https://harrydenley.com/EtherAddressLookup/phishing.html#http://www.empowr.com/#blacklisted
or see this http://prntscr.com/lnubmg
Help to get it up and running will be appreciated.

**Comment by 409H** [comment] 2018-11-29 23:45
Closing. Duplicate of https://github.com/409H/EtherAddressLookup/issues/1038

The application is asking users for their private keys and sending them to their backend - this is a big no no.

You can disable "Warn of Blacklisted Domains" if you wish to use empowr

**Closed by 409H** 2018-11-29 23:45 UTC
